### ISSUE TITLE
Rampage pickup om0

### ISSUE THREAD

**Issue by NABN00B** [Sergeanur/SCFIX-Liberty#2] opened 2024-08-10 12:54 UTC
![image](https://github.com/user-attachments/assets/ff66b5d3-e2fb-472f-b7ec-ef908a9e273e)

**Comment by Powdinet** [comment] 2024-08-10 13:04
The issue is in rampage.sc. The script doesn't check for on_mission before checking each rampage. https://github.com/Sergeanur/SCFIX-Liberty/blob/beta/2024.08.10/Main/Industrial/rampage.sc#L127

Adding a blind on_mission check would not be a good idea, however. HAS_PICKUP_BEEN_COLLECTED only works for the last 20 pickups, so if the player picks up the rampage, goes on_mission 1, and picks up 20 more pickups, the rampage would be lost forever. There needs to be a check in place to restore rampage pickups in these cases.

A similar issue happens with the save menu. Saving during a rampage and reloading the save will remove that rampage forever.

**Comment by Sergeanur** [comment] 2024-08-10 14:13
Could you check [beta/2024.08.10_2](https://github.com/Sergeanur/SCFIX-Liberty/releases/tag/beta%2F2024.08.10_2) if this is fixed now? Also the save thing too

**Comment by Powdinet** [comment] 2024-08-10 14:43
Yeah, seems good!

**Closed as completed** 2024-08-10 14:53 UTC
